version: "3.9"

x-base: &base
  restart: always
  build: .
  env_file:
    - .env
  depends_on:
    kafka:
      condition: service_healthy

services:
  bot:
    <<: *base
    container_name: bot
    entrypoint: ["uv", "run", "src/main.py"]
    build:
      context: gmonitor-bot
      dockerfile: Dockerfile

  faststream-gmonitor-bot:
    <<: *base
    container_name: faststream-gmonitor-bot
    entrypoint: ["uv", "run", "faststream", "run", "src/broker:app"]
    build:
      context: gmonitor-bot
      dockerfile: Dockerfile

  faststream-gmonitor-api-gateway:
    <<: *base
    container_name: faststream-gmonitor-api-gateway
    entrypoint: ["uv", "run", "faststream", "run", "src/broker:app"]
    build:
      context: gmonitor-api-gateway
      dockerfile: Dockerfile

  kafka:
    image: 'bitnami/kafka:4.0.0'
    container_name: kafka
    expose:
      - "9092"
      - "9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://80.93.218.46:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9094:9094"
    healthcheck:
      test: kafka-topics.sh --bootstrap-server localhost:9092 --list
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8082:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: ${GUI_LOGIN}
      SPRING_SECURITY_USER_PASSWORD: ${GUI_PASSWORD}
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  kafka_data:
